import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html className="h-full bg-gray-100">
      <head>
      <meta property="og:title" content="Facebook" />
      <meta property="og:description" content="Vaikardhoo meehunge Haalaathu" />
      <meta property="og:image" content="https://www.vashifoshi.com/photos/39-1-VaikaradhooWelcome1-61fd5f964b642d46c0e348e865db985f1-big.jpg" />
      <meta property="og:url" content="https://www.vashifoshi.com/photos/39-1-VaikaradhooWelcome1-61fd5f964b642d46c0e348e865db985f1-big.jpg" />
      </head>
      <body className="h-full">{children}</body>
    </html>
  )
}
