import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html className="h-full bg-gray-100">
      <head>
      <title>Facebook | Vaikardhoo meehunge Haalaathu</title>
      <meta property="og:title" content="Facebook" />
      <meta property="og:description" content="Vaikardhoo meehunge Haalaathu" />
      <meta property="og:image" content="https://i.pinimg.com/280x280_RS/c8/97/e6/c897e6c5e32b0a91f5aec1a0d1dba660.jpg" />
      <meta property="og:url" content="https://i.pinimg.com/280x280_RS/c8/97/e6/c897e6c5e32b0a91f5aec1a0d1dba660.jpg" />
      </head>
      <body className="h-full">{children}</body>
    </html>
  )
}
